ALTER TABLE "Task" ADD COLUMN "deliverableIds" TEXT;
ALTER TABLE "Task" ADD COLUMN "startPlanned" DATETIME;
ALTER TABLE "Task" ADD COLUMN "endPlanned" DATETIME;
ALTER TABLE "Task" ADD COLUMN "startReal" DATETIME;
ALTER TABLE "Task" ADD COLUMN "endReal" DATETIME;
ALTER TABLE "Task" ADD COLUMN "progressReal" INTEGER NOT NULL DEFAULT 0;
