ALTER TABLE "Task" ADD COLUMN "phase" TEXT;
ALTER TABLE "Task" ADD COLUMN "plannedStart" DATETIME;
ALTER TABLE "Task" ADD COLUMN "plannedEnd" DATETIME;
ALTER TABLE "Task" ADD COLUMN "actualStart" DATETIME;
ALTER TABLE "Task" ADD COLUMN "actualEnd" DATETIME;
ALTER TABLE "Task" ADD COLUMN "progressActual" INTEGER NOT NULL DEFAULT 0;

UPDATE "Task"
SET "status" = 'NOT_STARTED'
WHERE "status" = 'TODO';
